WEB3#-2300: add staking api
fireblocks/fireblocks-openapi-spec pull request #4
Opened 2023-11-01 15:42 UTC by yahavamar

2023-11-03 16:41 UTC, dsahni requested changes
1. Added suggestions to make the summary names shorter so they show up better in dev portal

2. Added an example to the first endpoint with beta language (note the multiline syntax) in `description` param. @yahavamar Can you please add similar messaging to the rest of the endpoints?

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        summary: 'Get chain-specific, staking-related information summary'
```suggestion
        summary: 'Get chain-specific staking summary'
```

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        summary: 'Execute a chain-specific staking action'
```suggestion
        summary: 'Execute a staking action'
```

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        summary: 'Get staking summary details per-chain'
```suggestion
        summary: 'Get staking summary details'
```

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        summary: 'Get staking positions details by staking position id'
```suggestion
        summary: 'Get staking positions details'
```

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        summary: 'List staking validators details by staking chain'
```suggestion
        summary: 'List staking validators details'
```

2023-11-03 16:41 UTC, dsahni commented on open_api_spec.yml
> +        description: Return an alphabetical list of supported chains.
```suggestion
        description: |-
          Return an alphabetical list of supported chains.  </br>
          **Note:** These endpoints are currently in beta and might be subject to changes.
```

2023-11-16 08:39 UTC, yahavamar commented on open_api_spec.yml
> +        summary: 'Execute a chain-specific staking action'
Done

2023-11-20 19:00 UTC, merged